sipy/index/urls.py
from django.urls import path,include
from .views import index, blog


app_name = 'index'
urlpatterns = [
    path('', index, name='index'),  # The home page
    path('blog/<slug>', blog, name='blog'),
]

sipy/sipy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sipy/index/models.py
from django.db import models
from django.contrib.auth.models import User  # Import the built-in User model
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.dispatch import receiver

# Create your models here.


class Ourteam(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    position = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    description = models.TextField()

    def __str__(self):
        return self.name
    
class Contact(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField( blank=True, null=True)
    phone = models.CharField(max_length=20,  blank=True, null=True)
    message = models.TextField()
    
    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogs')  # ForeignKey to User
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    short_description=CKEditor5Field('Text', config_name='short description')
    description=CKEditor5Field('Text', config_name='description')
    slug = models.SlugField(unique=True, blank=True, null=True)
    date = models.DateField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title or "Untitled Blog"


# Automatically generate the slug from the title
@receiver(pre_save, sender=Blog)
def auto_generate_slug(sender, instance, **kwargs):
    if instance.title and not instance.slug:
        instance.slug = slugify(instance.title)

sipy/index/views.py
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Ourteam, Contact, Blog
from django.conf import settings

def index(request):
    ourteam = Ourteam.objects.all()
    blog = Blog.objects.all()

    if request.method == 'POST':
        name = request.POST.get("name")
        email = request.POST.get("email", None)
        phone = request.POST.get("phone")
        message = request.POST.get("message", "")

        # Save the contact information
        Contact.objects.create(name=name, email=email, phone=phone, message=message)

        # Render email content using an HTML template
        subject = "New Contact Form Submission"
        context = {
            'name': name,
            'email': email,
            'phone': phone,
            'message': message,
        }
        email_body = render_to_string('contact_email.html', context)

        to_email = settings.EMAIL_HOST_USER  # Replace with your email address
        from_email = settings.ADMIN_EMAIL  # Replace with a valid from address
        
        try:
            email_message = EmailMessage(subject, email_body, from_email, [to_email])
            email_message.content_subtype = 'html'  # Set the email content to HTML
            email_message.send()
            messages.success(request, "Your message has been submitted successfully!")
        except Exception as e:
            messages.error(request, f"An error occurred while sending the email: {e}")

        return redirect("index")

    context = {
        'ourteam': ourteam,
        'blog': blog,
    }
    
    return render(request, 'index.html', context)


def blog (request, slug):
    blog = Blog.objects.get(slug=slug)
    all_blogs = Blog.objects.exclude(id=blog.id)[:3]

    return render(request, 'blog.html', {'blog': blog, 'all_blogs': all_blogs})

sipy/index/templates/blog.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}

<style>

</style>

{% block content %}


<section class="bg-[#f0f6fc] font-sans leading-relaxed tracking-wide">
    <div class="max-w-screen-xl mx-auto py-8 px-4 lg:px-8">
        <div class="grid grid-cols-1 gap-8 lg:grid-cols-4 lg:gap-8 lg:grid-flow-row-dense">
            <!-- Sidebar -->
            <aside class="lg:col-span-1 bg-white shadow-lg rounded-lg p-6 order-last lg:order-first">
                <h2 class="text-xl font-bold mb-4 border-b pb-2">Latest Blogs</h2>
                <ul class="space-y-4">
                    {% for blog in all_blogs %}
                    <li>
                        <a href="{% url 'index:blog' blog.slug %}" class="text-primary hover:underline hover:text-secondary">{{ blog.title }}</a>
                        <p class="text-sm text-gray-500">{{ blog.date }}</p>
                    </li>
                    {% endfor %}
                </ul>

                <h2 class="text-xl font-bold mt-6 mb-4 border-b pb-2">Follow Us</h2>
                <div class="flex space-x-4">
                    <a href="https://www.facebook.com/profile.php?id=61569742269323" target="_blank" class="text-secondary hover:text-blue-600">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16" class="w-6 h-6">
                            <path d="M8 0C3.582 0 0 3.582 0 8c0 4.015 2.926 7.323 6.751 7.876v-5.572H4.843v-2.304h1.908V6.004c0-1.892 1.137-2.936 2.876-2.936.832 0 1.703.15 1.703.15v1.872h-.96c-.946 0-1.239.588-1.239 1.193v1.444h2.101l-.335 2.304h-1.766v5.572C13.074 15.323 16 12.015 16 8c0-4.418-3.582-8-8-8z"/>
                        </svg>
                    </a>
                    <a href="https://x.com/SIPYCARE" target="_blank" class="text-secondary hover:text-blue-400">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16" class="w-6 h-6">
                            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.141 0-.283-.006-.425A6.684 6.684 0 0 0 16 3.542a6.56 6.56 0 0 1-1.889.518A3.301 3.301 0 0 0 15.555 2a6.573 6.573 0 0 1-2.084.797A3.286 3.286 0 0 0 7.875 4.03a9.325 9.325 0 0 1-6.766-3.429 3.289 3.289 0 0 0 1.016 4.381A3.323 3.323 0 0 1 .64 5.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115c-.211 0-.417-.02-.616-.057a3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045 9.344 9.344 0 0 0 5.026 1.472"/>
                        </svg>
                    </a>
                    <a href="https://www.instagram.com/sipycare" target="_blank" class="text-secondary hover:text-pink-600">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 16" class="w-6 h-6">
                            <path d="M8 0C5.33 0 5.048.013 3.837.073 2.63.132 1.843.325 1.283.57.6.85.157 1.243.038 1.862-.127 2.638 0 4.128 0 7.952c0 3.821-.127 5.313.038 6.089.12.619.563 1.012 1.245 1.292.56.245 1.347.438 2.554.497 1.211.06 1.493.073 4.162.073s2.95-.013 4.162-.073c1.207-.059 1.994-.252 2.554-.497.683-.28 1.126-.673 1.245-1.292.165-.776.038-2.268.038-6.089 0-3.824.127-5.313-.038-6.089-.12-.619-.563-1.012-1.245-1.292-.56-.245-1.347-.438-2.554-.497C10.95.013 10.67 0 8 0zm0 1.234c2.637 0 2.91.013 3.935.071.92.054 1.42.227 1.747.379.432.211.743.496.892.891.152.43.325.827.379 1.747.058 1.024.071 1.297.071 3.935s-.013 2.91-.071 3.935c-.054.92-.227 1.42-.379 1.747-.211.432-.496.743-.891.892-.431.152-.828.325-1.748.379-1.024.058-1.297.071-3.935.071s-2.91-.013-3.935-.071c-.92-.054-1.42-.227-1.747-.379-.432-.211-.743-.496-.892-.891-.152-.43-.325-.827-.379-1.747C1.247 10.91 1.234 10.637 1.234 8s.013-2.91.071-3.935c.054-.92.227-1.42.379-1.747.211-.432.496-.743.891-.892.431-.152.828-.325 1.748-.379C5.09 1.247 5.363 1.234 8 1.234z"/>
                            <path d="M8 3.842a4.158 4.158 0 1 0 0 8.316 4.158 4.158 0 0 0 0-8.316zm0 6.842a2.684 2.684 0 1 1 0-5.368 2.684 2.684 0 0 1 0 5.368z"/>
                            <circle cx="12.228" cy="3.772" r="1.2"/>
                        </svg>
                    </a>
                    
                </div>
            </aside>

            <!-- Main Content -->
            <main class="lg:col-span-3 bg-white shadow-md rounded-lg p-6">
                <h1 class="text-3xl font-bold mb-4">{{ blog.title }}</h1>
                <p class="text-gray-500 mb-6">Published on {{ blog.date }} | by {{ blog.author }}</p>
                <img src="{{ blog.image.url }}" alt="Blog Image" class="w-full h-auto rounded-md mb-6">
                <div class=" space-y-6 blog-content">
                    {{ blog.description | safe }}
                </div>
            </main>
        </div>
    </div>
</section>


{% endblock %}

sipy/index/templates/contact_email.html
<!DOCTYPE html>
<html>
<head>
    <title>New Contact Form Submission</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f9f9f9;
            padding: 20px;
        }
        .email-container {
            background-color: #ffffff;
            border: 1px solid #dddddd;
            padding: 20px;
            max-width: 600px;
            margin: auto;
        }
        .header {
            font-size: 20px;
            margin-bottom: 20px;
        }
        .footer {
            margin-top: 20px;
            font-size: 12px;
            color: #888888;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">New Message from {{ name }}</div>
        <p><strong>Email:</strong> {{ email }}</p>
        <p><strong>Phone:</strong> {{ phone }}</p>
        <p><strong>Message:</strong></p>
        <p>{{ message }}</p>
        <div class="footer">
            This is an automated message. Please do not reply.
        </div>
    </div>
</body>
</html>

sipy/index/templates/includes/blogView.html
{% load static %}
<!-- Splide CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide/dist/css/splide.min.css">

<section class="max-w-screen-xl mx-auto mt-20" id="blog">
    <h2 class="text-center text-3xl font-bold md:text-4xl md:text-start">Want to Learn More?</h2>
    <p class="text-gray-700 text-base font-normal text-center mt-3 md:text-lg md:text-start">
        See how we curate the perfect equity portfolio for you in our blog.
    </p>
    <div class="splide mt-5" id="blog-carousel">
        <!-- Splide Track -->
        <div class="splide__track">
            <ul class="splide__list">
                {% for blog in blog %}
                <li class="splide__slide">
                    <div class="rounded-xl shadow-lg shadow-slate-200 p-4">
                        <div class="card-image">
                            <img class="w-full h-48 rounded-xl" src="{{ blog.image.url }}" alt="{{ blog.title }}" />
                        </div>
                        <div class="card-content">
                            <h3 class="card-title text-xl font-bold text-start mt-4 hover:text-primary cursor-pointer">
                                {{ blog.title }}
                            </h3>
                            <span class="text-sm text-secondary font-normal text-end md:text-sm md:text-end">By {{ blog.date }}</span>
                            <p class="card-text text-sm font-normal text-start mt-3 md:text-lg md:text-start">
                                {{ blog.short_description | truncatewords:10 | safe }}
                            </p>
                            <a href="{% url 'index:blog' blog.slug %}" class="text-primary text-sm font-semibold mt-4 hover:text-secondary">
                                Read More
                            </a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>

        <!-- Custom Navigation Buttons -->
        <div class="splide-nav">
            <button class="splide-prev bg-primary text-white w-10 h-10 rounded-full flex items-center justify-center">
                &larr;
            </button>
            <button class="splide-next bg-primary text-white w-10 h-10 rounded-full flex items-center justify-center">
                &rarr;
            </button>
        </div>
    </div>
</section>

<!-- Splide JS -->
<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide/dist/js/splide.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Initialize Splide
        const splide = new Splide('#blog-carousel', {
            type: 'loop',
            perPage: 3,
            gap: '1rem',
            breakpoints: {
                640: { perPage: 1 },
                768: { perPage: 2 },
            },
            pagination: false,
            arrows: false, // Disable default arrows
        });

        splide.mount();

        // Custom Navigation Buttons
        document.querySelector('.splide-prev').addEventListener('click', () => splide.go('<'));
        document.querySelector('.splide-next').addEventListener('click', () => splide.go('>'));
    });
</script>

sipy/index/templates/includes/calculator.html
{% load static %}
 
<section class="bg-primary p-10 mt-20" id="calculator">
    <div class="flex flex-col md:flex-row items-center justify-between gap-20 max-w-screen-xl mx-auto">
        <div class="w-full md:w-1/2 grid grid-cols-1 md:grid-cols-2 gap-4">
            {% comment %} <div class="">
                <h2 class="text-2xl font-medium leading-6 text-white md:text-4xl ">Check How<br> Much You Save With Us</h2>
            </div>

            <div class="flex gap-3 flex-col">
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
            </div>

            <div class="flex gap-3 flex-col mt-4">
                <h3 class="text-white text-lg font-semibold">Normal funds</h3>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
            </div>

            <div class="flex gap-3 flex-col mt-4">
                <h3 class="text-white text-lg font-semibold">with SIPY</h3>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
                <input class="w-3/4 p-1.5 rounded-md bg-[#2687e8]"/>
            </div> {% endcomment %}
            <h2 class="text-4xl font-bold text-center  leading-10 text-white md:text-4xl md:leading-10 md:text-start ">Check How Much You Save With Us</h2>
        </div>
        <div class="w-full flex justify-center md:justify-end md:w-1/2">
            {% comment %} <div class="bg-blue-500 p-6 flex justify-center items-center h-64">
                <canvas id="myChart" class="w-full"></canvas>
            </div> {% endcomment %}
            <a href="{% static 'images/SIPY_Cost_advantage.xlsx' %}" download><button class="bg-secondary px-8 py-5 text-white font-semibold text-xl rounded-full ">Click Here!</button></a>
        </div>
    </div>
</section>


  

sipy/index/templates/includes/contact.html
{% load static %}

<section class="container mx-auto mt-20" id="contact">

<div class="max-w-screen-xl mt-8 mx-auto p-10 shadow-lg shadow-gray-200 rounded-3xl">
    {% if messages %}
    <div>
        {% for message in messages %}
            <div class="alert {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="flex flex-col gap-8 mt-8 p-0  md:p-10 md:flex-row">
        <div class="w-full flex items-center md:w-1/2 ">
            <img class="w-full " src="{% static 'images/Contact-us.png' %}" alt="Hero Image">
        </div>
        <div class="w-full md:w-1/2">
            <h2 class="text-2xl font-bold w-full text-primary text-center md:text-start md:text-4xl ">Need a More Personalised Plan?Reach Out to Us!</h2>

            <form class="mt-4" method="post">
                {% csrf_token %}
                <div class="mt-3">
                    <label for="name" class="text-lg font-medium text-gray-500 ">Name<span class="text-red-500 ml-1">*</span></label>
                    <input id="name" type="text" name="name" class="p-3 w-full text-gray-900 border border-gray-300 rounded-md mt-1" placeholder="john Doe" required/>
                </div>
                <div class="mt-4">
                    <label for="email" class="text-lg font-medium text-gray-500">Email</label>
                    <input id="email" name="email" type="email" class="p-3 w-full text-gray-900 border border-gray-300 rounded-md mt-1" placeholder="johndue@mail.com"/>
                </div>
                <div class="mt-4">
                    <label for="phone" class="text-lg font-medium text-gray-500">Phone Number<span class="text-red-500 ml-1">*</span>(Don't worry, we won't spam you!)</label>
                    <input id="phone" name="phone" type="text"  class="p-3 w-full text-gray-900 border border-gray-300 rounded-md mt-1" placeholder="00000 00000" required/>
                </div>
                <div class="mt-4">
                    <label for="message" class="text-lg font-medium text-gray-500">Brief<span class="text-red-500 ml-1">*</span></label>
                    <textarea id="message" name="message" type="text" class="p-3 w-full h-36 text-gray-900 border border-gray-300 rounded-md mt-1" placeholder="If you’d like us to know something is specific, let us know" required></textarea>
                </div>

                <button type="submit" class="w-full p-5 bg-secondary text-white font-bold rounded-full mt-10 text-2xl">SUBMIT</button>
            </form>
        </div>
    </div>
</div>
</section>

sipy/index/templates/includes/sure.html
{% load static %}

<section class=" px-4 w-full sure">
    <div class="max-w-screen-xl mt-8 mx-auto">
        <h2 class="text-center text-3xl font-bold md:text-4xl ">Still Not Sure?</h2>
        <p class="text-gray-700 text-base font-normal text-center mt-3 md:text-lg ">Read What Industry Veterans Say About the Benefits of Index and ETF Investing</p>
        <div class="flex flex-col gap-5 mt-8 md:flex-row ">
            <div class=" w-full p-6 flex flex-col gap-6 bg-[#f4f9e5] rounded-3xl md:flex-row md:w-1/2">
                <div class="w-full bg-red-800 h-56 md:w-1/3 sure-img sure-img1 ">
                    
                </div>
                <div class="w-full flex flex-col justify-between md:w-2/3">
                    <p class="text-base font-normal mt-2">The winning formula for success in investing is
                    owning the entire stock market through an
                    index fund, and then doing nothing. Just stay
                    the course.”
                    </p>
                    <div class="flex flex-col">
                        <h3 class="text-lg font-bold text-gray-900 mt-3">John C Bogle</h3>
                        <a href="https://en.wikipedia.org/wiki/The_Vanguard_Group" target="_blank" class="text-sm text-primary">Founder of Vanguard</a>
                    </div>
                </div>
            </div>
            <div class=" w-full p-6 flex flex-col gap-6 bg-[#ebedf7] rounded-3xl md:flex-row md:w-1/2">
                <div class="w-full bg-red-800 h-56 md:w-1/3 sure-img sure-img2 ">
                    
                </div>
                <div class="w-full flex flex-col justify-between md:w-2/3">
                    <p class="text-base font-normal mt-2">By periodically investing in an index fund, the knownothing investor can actually outperform most
                    investment professionals</p>
                    <div class="flex flex-col">
                        <h3 class="text-lg font-bold text-gray-900 mt-3">Warren Buffet</h3>
                        <a href="https://en.wikipedia.org/wiki/Berkshire_Hathaway" target="_blank" class="text-sm text-primary">Chairperson of Berkshire Hathway</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

sipy/index/templates/index.html
{% extends 'base.html' %}

{% block title %}Sipy{% endblock %}

{% block content %}

    {% include 'includes/hero.html' %}
    {% include 'includes/whysipy.html' %}
    {% include 'includes/sure.html' %}
    {% include 'includes/calculator.html' %}
    {% include 'includes/blogView.html' %}
    {% include 'includes/contact.html' %}
    {% include 'includes/whoweare.html' %}

{% endblock %}

sipy/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sipy{% endblock %}</title>
    
    <link href="https://fonts.googleapis.com/css2?family=Figtree:wght@400;600&family=Poppins:wght@400;600&family=Darker+Grotesque:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <link rel="stylesheet" href="{% static 'css/Style.css' %}">
    <link href="{% static 'css/Tailwind.css' %}" rel="stylesheet">
    
    <style>
      body{
        margin:0;
        padding:0;
      }
    </style>
</head>
<body>
    <!-- Navigation Bar -->
    <header class="container mx-auto p-4 mt-7 ">


        <nav class="bg-white border-gray-200 ">
            <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto">
              <a href="{% url 'index:index' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
                  <img src="{% static 'images/SIPY_logo.png' %}" class="h-12 mr-3" alt="Sipy Logo">
              </a>
              <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
                  <span class="sr-only">Open main menu</span>
                  <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                  </svg>
              </button>
              <div class="hidden w-full md:block md:w-auto" id="navbar-default">
                <ul class="font-bold font-body text-2xl flex flex-col gap-4 p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:gap-8 md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white">
                  <li>
                    <a href="{% url 'index:index' %}#whysipy" class="block py-2 px-3 text-gray-900 bg-secondary rounded md:bg-transparent md:hover:text-secondary md:p-0 " aria-current="page">Why SIPY</a>
                  </li>
                  <li>
                    <a href="{% url 'index:index' %}#calculator" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary md:p-0">Calculator</a>
                  </li>
                  <li>
                    <a href="{% url 'index:index' %}#blog" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary md:p-0">blog</a>
                  </li>
                  <li>
                    <a href="{% url 'index:index' %}#whoweare" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-secondary md:p-0">Who We Are</a>
                  </li>
                  <li class="">
                    <a href="{% url 'index:index' %}#contact" class="block py-2 px-3 rounded-full text-gray-900  hover:bg-gray-100 md:hover:bg-transparent md:bg-secondary md:hover:bg-primary md:px-10 md:py-1 md:text-white md:w-full md:border-0">Contact</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
    </header>

    <!-- Main Content -->
        {% block content %}
  
        {% endblock %}

    <!-- Footer -->
      <section class="p-2 mt-20 bg-primary md:p-10" >
        <div
          class="max-w-screen-xl mx-auto flex p-10 flex-col justify-between md:flex-row pb-10"
        >
          <div class="w-full md:w-1/3 md:py-10">
            <img
              src="{% static 'images/SIPY Logo-white.png' %}"
              class="h-24"
              alt="Flowbite Logo"
            />
            <p class="mt-6  text-white text-base">
              Simplified Investments Personalised for You
              31/2B, Nagaloothu Street, Kanchipuram, 631501
              ARN - 190682, Ph- +91-7022411404
              Mail – hello@sipy.in
            </p>
          </div>
          <div class="w-full flex md:w-1/3 mt-10 flex-col py-2 md:px-10 md:py-10 md:mt-0">
            <div class="flex flex-row justify-between py-0">
              <a
                href="https://www.facebook.com/profile.php?id=61569742269323"
                target="_blank"
                style="text-decoration: none"
              >
                <i class="fab fa-facebook" style="color: #ffffff; font-size: 40px"></i>
              </a>
      
      
              <a
                href="https://www.linkedin.com/company/sipycare"
                target="_blank"
                style="text-decoration: none"
              >
                <i
                  class="fab fa-linkedin"
                  style="color: #ffffff; font-size: 40px"
                ></i>
              </a>
      
      
              <a
                href="https://www.instagram.com/sipycare"
                target="_blank"
                style="text-decoration: none"
              >
                <i
                  class="fab fa-instagram"
                  style="color: #ffffff; font-size: 40px"
                ></i>
              </a>
              <a
                href="https://x.com/SIPYCARE"
                target="_blank"
                style="text-decoration: none"
              >
              <img src="{% static 'images/twitter.png' %}" alt="x" style="width: 38px; height: 38px;">
              
              </a>
            </div>
            <p class="mt-6 text-white text-sm leading-6">
              Mutual Fund investments are subject to market risks. Please read all
              scheme related documents carefully before investing. Past performance is
              not an
            </p>
          </div>
        </div>
      
        <div class="">
          <hr class="my-2 font-bold border-gray-300" />
          <p class ="mt-5 text-center text-blue-500">&copy; 2024 <a href="https://sipy.in" class="text-gray-200 hover:underline">Sipy.in</a>. Developed by <a href="https://ec4you.in" class="text-gray-200 hover:underline ">ec4you</a>. All rights reserved.</p>
        </div>
      </section>


    {% block scripts %}

        <script>
                    // Get references to the menu toggle button and menu list
        const menuToggle = document.getElementById('menu-toggle');
        const menuList = document.getElementById('menu-list');

        // Add event listener to toggle the menu visibility
        menuToggle.addEventListener('click', () => {
            menuList.classList.toggle('hidden'); // Toggle the 'hidden' class
        });

        </script>

    {% endblock %}
</body>

<script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>

</html>

sipy/templates/includes/header.html
{% load static %}

<div class="flex">
    <div class="">
        <h4 class="text-3xl text-[#0066cc] font-bold">SIMPLIFIED INVESTMENTS PERSONLIZED FOR YOU</h4>
    </div>
    <div class="menu">
        <ul>
            <li><a href="#">Why SIPY</a></li>
            <li><a href="#">Calculator</a></li>
            <li><a href="#">Portfolios</a></li>
            <li><a href="#">Who We Are</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </div>
</div>